package faculife

class BootStrap {

    def init = { servletContext ->
        (new Materia(codigo: "6103", nombre: "ANALISIS MATEMATICO II A")).save()
        (new Materia(codigo: "6106", nombre: "PROBABILIDAD Y ESTADISTICA A")).save()
        (new Materia(codigo: "6107", nombre: "MATEMATICA DISCRETA")).save()
        (new Materia(codigo: "6108", nombre: "ALGEBRA II A")).save()
        (new Materia(codigo: "6109", nombre: "PROBABILIDAD Y ESTADISTICA B")).save()
        (new Materia(codigo: "6110", nombre: "ANALISIS MATEMATICO III A")).save()
        (new Materia(codigo: "6112", nombre: "ANALISIS MATEMATICO III B")).save()
        (new Materia(codigo: "6113", nombre: "ANALISIS MATEMATICO III C")).save()
        (new Materia(codigo: "6114", nombre: "MATEMATICA ESPECIAL PARA ING. QUIMICA")).save()
        (new Materia(codigo: "6116", nombre: "MATEMATICA PARA INGENIEROS")).save()
        (new Materia(codigo: "8101", nombre: "ANALISIS MATEMATICO II")).save()
        (new Materia(codigo: "8102", nombre: "ALGEBRA II")).save()
        (new Materia(codigo: "8103", nombre: "PROBABILIDAD Y ESTADISTICA A")).save()
        (new Materia(codigo: "8104", nombre: "PROBABILIDAD Y ESTADÍSITCA B")).save()
        (new Materia(codigo: "8105", nombre: "ANALISIS MATEMATICO III A")).save()
        (new Materia(codigo: "8106", nombre: "ANALISIS MATEMATICO III B")).save()
        (new Materia(codigo: "8108", nombre: "ANÁLISIS MATRICIAL Y MÉTODOS NUMÉRICOS")).save()
        (new Materia(codigo: "8109", nombre: "PROBABILIDAD")).save()
        (new Materia(codigo: "8111", nombre: "MATEMÁTICA DISCRETA")).save()
        (new Materia(codigo: "6201", nombre: "FISICA I A")).save()
        (new Materia(codigo: "6203", nombre: "FISICA II A")).save()
        (new Materia(codigo: "6204", nombre: "FISICA II B")).save()
        (new Materia(codigo: "6205", nombre: "FISICA III")).save()
        (new Materia(codigo: "6206", nombre: "MECANICA I")).save()
        (new Materia(codigo: "6207", nombre: "MECANICA II")).save()
        (new Materia(codigo: "6208", nombre: "ELECTROMAGNETISMO A")).save()
        (new Materia(codigo: "6209", nombre: "ELECTROMAGNETISMO B")).save()
        (new Materia(codigo: "6210", nombre: "FISICA DEL ESTADO SOLIDO")).save()
        (new Materia(codigo: "6211", nombre: "MECANICA RACIONAL")).save()
        (new Materia(codigo: "6213", nombre: "FISICA III C")).save()
        (new Materia(codigo: "6215", nombre: "FISICA III D")).save()
        (new Materia(codigo: "6218", nombre: "FÍSICA DE FLUIDOS")).save()
        (new Materia(codigo: "8201", nombre: "FISICA I")).save()
        (new Materia(codigo: "8202", nombre: "FISICA II")).save()
        (new Materia(codigo: "8203", nombre: "FISICA III")).save()
        (new Materia(codigo: "8204", nombre: "MECÁNICA RACIONAL")).save()
        (new Materia(codigo: "8205", nombre: "FÍSICA DEL ESTADO SÓLIDO")).save()
        (new Materia(codigo: "8206", nombre: "ELECTROMAGNETISMO")).save()
        (new Materia(codigo: "8207", nombre: "FISICA III B")).save()
        (new Materia(codigo: "6301", nombre: "QUIMICA")).save()
        (new Materia(codigo: "6302", nombre: "QUIMICA I")).save()
        (new Materia(codigo: "6305", nombre: "QUIMICA ANALITICA")).save()
        (new Materia(codigo: "6307", nombre: "QUIMICA FISICA II")).save()
        (new Materia(codigo: "6310", nombre: "TERMODINAMICA ESTADISTICA")).save()
        (new Materia(codigo: "6311", nombre: "QUIMICA APLICADA A")).save()
        (new Materia(codigo: "6313", nombre: "QUÍMICA INORGÁNICA")).save()
        (new Materia(codigo: "6314", nombre: "QUÍMICA ORGÁNICA")).save()
        (new Materia(codigo: "6315", nombre: "QUÍMICA ANALÍTICA INSTRUMENTAL")).save()
        (new Materia(codigo: "6316", nombre: "QUÍMICA FÍSICA")).save()
        (new Materia(codigo: "8301", nombre: "QUIMICA")).save()
        (new Materia(codigo: "8302", nombre: "QUÍMICA APLICADA")).save()
        (new Materia(codigo: "6402", nombre: "ESTABILIDAD II A")).save()
        (new Materia(codigo: "6403", nombre: "COMPORTAMIENTO DE LOS MATERIALES")).save()
        (new Materia(codigo: "6404", nombre: "ESTATICA Y RESISTENCIA DE MATERIALES A")).save()
        (new Materia(codigo: "6405", nombre: "ESTATICA Y RESISTENCIA DE MATERIALES B")).save()
        (new Materia(codigo: "6407", nombre: "ESTABILIDAD III A")).save()
        (new Materia(codigo: "6408", nombre: "MECANICA DE SUELOS")).save()
        (new Materia(codigo: "6410", nombre: "ESTABILIDAD IV")).save()
        (new Materia(codigo: "6411", nombre: "ESTABILIDAD I B")).save()
        (new Materia(codigo: "6412", nombre: "ESTABILIDAD II B")).save()
        (new Materia(codigo: "6413", nombre: "ESTABILIDAD III B")).save()
        (new Materia(codigo: "6414", nombre: "METODO DE LOS ELEMENTOS FINITOS")).save()
        (new Materia(codigo: "6415", nombre: "ESTABILIDAD IV B")).save()
        (new Materia(codigo: "6416", nombre: "ANALISIS EXPERIMENTAL DE TENSIONES")).save()
        (new Materia(codigo: "6417", nombre: "SEGURIDAD ESTRUCTURAL")).save()
        (new Materia(codigo: "8401", nombre: "INTRODUCCIÓN A LA INGENIERÍA CIVIL")).save()
        (new Materia(codigo: "8402", nombre: "ESTABILIDAD I")).save()
        (new Materia(codigo: "8403", nombre: "ESTABILIDAD II")).save()
        (new Materia(codigo: "8404", nombre: "COMPORTAMIENTO DE MATERIALES")).save()
        (new Materia(codigo: "8405", nombre: "ESTATICA Y RESISTENCIA DE LOS MATERIALES")).save()
        (new Materia(codigo: "8406", nombre: "ESTABILIDAD III")).save()
        (new Materia(codigo: "8407", nombre: "MECANICA DE SUELOS Y GEOLOGIA")).save()
        (new Materia(codigo: "8408", nombre: "ESTABILIDAD IV")).save()
        (new Materia(codigo: "8409", nombre: "METODO DE LOS ELEMENTOS FINITOS")).save()
        (new Materia(codigo: "8410", nombre: "ANALISIS EXPERIMENTAL DE TENSIONES")).save()
        (new Materia(codigo: "8411", nombre: "SEGURIDAD ESTRUCTURAL")).save()
        (new Materia(codigo: "8499", nombre: "TRABAJO PROFESIONAL DE INGENIERÍA CIVIL")).save()
        (new Materia(codigo: "6500", nombre: "TESIS DE INGENIERIA ELECTRICISTA")).save()
        (new Materia(codigo: "6501", nombre: "ELECTROTECNIA")).save()
        (new Materia(codigo: "6503", nombre: "ELECTROTECNIA GENERAL A")).save()
        (new Materia(codigo: "6504", nombre: "ELECTROTECNIA GENERAL B")).save()
        (new Materia(codigo: "6505", nombre: "ELECTROTECNIA GENERAL C")).save()
        (new Materia(codigo: "6506", nombre: "MAQUINAS ELECTRICAS")).save()
        (new Materia(codigo: "6509", nombre: "TEORIA DE CIRCUITOS")).save()
        (new Materia(codigo: "6510", nombre: "TEORIA DE CAMPOS")).save()
        (new Materia(codigo: "6511", nombre: "TECNOLOGIA DE MATERIALES I")).save()
        (new Materia(codigo: "6512", nombre: "TECNOLOGIA DE MATERIALES II")).save()
        (new Materia(codigo: "6513", nombre: "TEORIA DE MAQUINAS ELECTRICAS I")).save()
        (new Materia(codigo: "6514", nombre: "TEORIA DE MAQUINAS ELECTRICAS II")).save()
        (new Materia(codigo: "6516", nombre: "TRANSM. Y DIST. DE LA ENERGIA ELECTRICA")).save()
        (new Materia(codigo: "6517", nombre: "CENTRALES ELECTRICAS")).save()
        (new Materia(codigo: "6522", nombre: "APLICACIONES IND. DE LA ENER. ELECTRICA")).save()
        (new Materia(codigo: "6525", nombre: "CONSTRUCCIONES ELECTROMECANICAS")).save()
        (new Materia(codigo: "6528", nombre: "CONTROL DE PROCESOS INDUSTRIALES")).save()
        (new Materia(codigo: "6530", nombre: "ELECTROTECNIA GENERAL D")).save()
        (new Materia(codigo: "6533", nombre: "ECONOMIA DE LA ENERGIA ELECTRICA")).save()
        (new Materia(codigo: "6534", nombre: "LUMINOTECNIA")).save()
        (new Materia(codigo: "6536", nombre: "MEDIDAS ELECTRICAS")).save()
        (new Materia(codigo: "6537", nombre: "ENERGIAS RENOVABLES")).save()
        (new Materia(codigo: "6539", nombre: "METROLOGÍA Y TEC. CALIBRACIÓN ELÉCTRICA")).save()
        (new Materia(codigo: "6540", nombre: "USO EFICIENTE DE LA ENERGIA ELECTRICA")).save()
        (new Materia(codigo: "6541", nombre: "ESTACIONES TRANSFORMADORAS Y DISTRIBUC.")).save()
        (new Materia(codigo: "6542", nombre: "SISTEMAS DE PROTECCIONES ELECTRICAS")).save()
        (new Materia(codigo: "6543", nombre: "INGENIERIA DE LAS INSTALACIONES I")).save()
        (new Materia(codigo: "6548", nombre: "LABORATORIO DE INSTALACIONES ELÉCTRICAS")).save()
        (new Materia(codigo: "6599", nombre: "TRAB. PROFESIONAL DE ING. ELECTRICISTA")).save()
        (new Materia(codigo: "8500", nombre: "TESIS DE INGENIERÍA ELECTRICISTA")).save()
        (new Materia(codigo: "8501", nombre: "INTRODUCCIÓN A LA INGENIERÍA ELÉCTRICA")).save()
        (new Materia(codigo: "8502", nombre: "ELECTROTECNIA")).save()
        (new Materia(codigo: "8503", nombre: "TEORIA DE CIRCUITOS Y SISTEMAS")).save()
        (new Materia(codigo: "8504", nombre: "CAMPOS ELECTROMAGNETICOS")).save()
        (new Materia(codigo: "8505", nombre: "MEDIDAS ELECTRICAS")).save()
        (new Materia(codigo: "8506", nombre: "MAQUINAS ELECTRICAS I")).save()
        (new Materia(codigo: "8507", nombre: "MÁQUINAS ELÉCTRICAS II")).save()
        (new Materia(codigo: "8508", nombre: "TECNOLOGIA DE MATERIALES ELECTRICOS")).save()
        (new Materia(codigo: "8509", nombre: "DIAGNÓSTICOS ELÉCTRICOS Y ENSAYOS")).save()
        (new Materia(codigo: "8510", nombre: "CONSTRUCCIONES ELECTROMECÁNICAS")).save()
        (new Materia(codigo: "8511", nombre: "INSTALACIONES DE BAJA TENSIÓN Y LUMINOTECNIA")).save()
        (new Materia(codigo: "8513", nombre: "CENTRALES ELÉCTRICAS")).save()
        (new Materia(codigo: "8514", nombre: "TRANSMISIÓN Y DISTRIBUCIÓN DE LA ENERGÍA")).save()
        (new Materia(codigo: "8515", nombre: "PROTECCIONES ELECTRICAS Y EQUIPOS DE MANIOBRA")).save()
        (new Materia(codigo: "8516", nombre: "ELECTRÓNICA DE POTENCIA")).save()
        (new Materia(codigo: "8517", nombre: "ECONOMÍA DE LA ENERGÍA ELÉCTRICA")).save()
        (new Materia(codigo: "8519", nombre: "LUMINOTECNIA")).save()
        (new Materia(codigo: "8520", nombre: "ENERGÍAS RENOVABLES")).save()
        (new Materia(codigo: "8521", nombre: "USO EFICIENTE DE LA ENERGÍA ELÉCTRICA")).save()
        (new Materia(codigo: "8522", nombre: "METROLOGIA Y TECNICAS DE CALIBRACION")).save()
        (new Materia(codigo: "8525", nombre: "ESTACIONES TRANSFORMADORAS Y DE DISTRIBUCIÓN")).save()
        (new Materia(codigo: "8526", nombre: "DINÁMICA DE SEP")).save()
        (new Materia(codigo: "8535", nombre: "ELECTROTECNIA GENERAL C")).save()
        (new Materia(codigo: "8536", nombre: "MAQUINAS ELECTRICAS")).save()
        (new Materia(codigo: "8538", nombre: "ELECTROTECNIA GENERAL")).save()
        (new Materia(codigo: "8599", nombre: "TRABAJO PROFESIONAL DE INGENIERÍA")).save()
        (new Materia(codigo: "6601", nombre: "TECNICA DIGITAL")).save()
        (new Materia(codigo: "6602", nombre: "LABORATORIO")).save()
        (new Materia(codigo: "6603", nombre: "ELECTRONICA GENERAL")).save()
        (new Materia(codigo: "6604", nombre: "ELECTRONICA I")).save()
        (new Materia(codigo: "6605", nombre: "ELECTRONICA II")).save()
        (new Materia(codigo: "6606", nombre: "ANALISIS DE CIRCUITOS")).save()
        (new Materia(codigo: "6608", nombre: "CIRCUITOS ELECTRONICOS I")).save()
        (new Materia(codigo: "6609", nombre: "LABORATORIO DE MICROCOMPUTADORAS")).save()
        (new Materia(codigo: "6610", nombre: "CIRCUITOS ELECTRONICOS II")).save()
        (new Materia(codigo: "6612", nombre: "INTRODUCCION A PROYECTOS")).save()
        (new Materia(codigo: "6617", nombre: "SISTEMAS DIGITALES")).save()
        (new Materia(codigo: "6618", nombre: "TEORIA DE CONTROL I")).save()
        (new Materia(codigo: "6619", nombre: "CIRCUITO DE PULSOS")).save()
        (new Materia(codigo: "6620", nombre: "ORGANIZACION DE COMPUTADORAS")).save()
        (new Materia(codigo: "6621", nombre: "COMUNICACION DE DATOS")).save()
        (new Materia(codigo: "6624", nombre: "TEORIA DE INFORMACION Y CODIFICACION")).save()
        (new Materia(codigo: "6625", nombre: "DISPOSITIVOS SEMICONDUCTORES")).save()
        (new Materia(codigo: "6626", nombre: "ARQUITECTURAS PARALELAS")).save()
        (new Materia(codigo: "6627", nombre: "ELECTRONICA DE POTENCIA")).save()
        (new Materia(codigo: "6628", nombre: "TEORIA DE CONTROL II")).save()
        (new Materia(codigo: "6629", nombre: "CONTROL INDUSTRIAL DISTRIBUIDO")).save()
        (new Materia(codigo: "6630", nombre: "CONTROL NO LINEAL")).save()
        (new Materia(codigo: "6631", nombre: "IDENTIFICACION Y CONTROL ADAPTATIVO")).save()
        (new Materia(codigo: "6632", nombre: "ROBOTICA")).save()
        (new Materia(codigo: "6635", nombre: "TECNICA DIGITAL AVANZADA")).save()
        (new Materia(codigo: "6638", nombre: "PROCESAMIENTO DE SEÑALES I")).save()
        (new Materia(codigo: "6642", nombre: "COMUNICACIONES DIGITALES II")).save()
        (new Materia(codigo: "6643", nombre: "INGENIERIA BIOMEDICA")).save()
        (new Materia(codigo: "6644", nombre: "INSTRUMENTOS ELECTRONICOS")).save()
        (new Materia(codigo: "6646", nombre: "PROCESAMIENTO DEL HABLA")).save()
        (new Materia(codigo: "6648", nombre: "SEMINARIO DE ELECTRONICA")).save()
        (new Materia(codigo: "6649", nombre: "SISTEMAS BIOLOGICOS")).save()
        (new Materia(codigo: "6650", nombre: "TECNOLOGIA DE COMPONENTES")).save()
        (new Materia(codigo: "6651", nombre: "TEORIA DE DETECCION Y ESTIMACION")).save()
        (new Materia(codigo: "6653", nombre: "INSTRUMENTACION Y CONTROL DE PROCESOS")).save()
        (new Materia(codigo: "6657", nombre: "OPTOELECTRONICA")).save()
        (new Materia(codigo: "6662", nombre: "REDES DE COMPUTADORAS")).save()
        (new Materia(codigo: "6663", nombre: "REDES NEURONALES")).save()
        (new Materia(codigo: "6666", nombre: "SEMINARIO DE ELECTRONICA II")).save()
        (new Materia(codigo: "6667", nombre: "ACUSTICA")).save()
        (new Materia(codigo: "6669", nombre: "CRIPTOGRAFIA Y SEGURIDAD INFORMATICA")).save()
        (new Materia(codigo: "6670", nombre: "ESTRUCTURA DEL COMPUTADOR")).save()
        (new Materia(codigo: "6671", nombre: "SISTEMAS GRÁFICOS")).save()
        (new Materia(codigo: "6672", nombre: "SEÑALES E IMÁGENES EN BIOMEDICINA")).save()
        (new Materia(codigo: "6673", nombre: "INSTALACIONES E INSTRUMENTAC. BIOMEDICA")).save()
        (new Materia(codigo: "6674", nombre: "SEÑALES Y SISTEMAS")).save()
        (new Materia(codigo: "6675", nombre: "PROCESOS ESTOCÁSTICOS")).save()
        (new Materia(codigo: "6676", nombre: "TRANSMISIÓN Y RECEPC. DE COMUNICACIONES")).save()
        (new Materia(codigo: "6677", nombre: "SISTEMAS DE COMUNICACIONES")).save()
        (new Materia(codigo: "6678", nombre: "COMUNICACIONES DIGITALES Y ANALÓGICAS")).save()
        (new Materia(codigo: "6679", nombre: "LABORATORIO DE COMUNICACIONES")).save()
        (new Materia(codigo: "6680", nombre: "SISTEMAS INALÁMBRICOS")).save()
        (new Materia(codigo: "6681", nombre: "VIDEO Y REDES DE CABLE")).save()
        (new Materia(codigo: "6682", nombre: "PROPAGACIÓN Y SISTEMAS IRRADIANTES")).save()
        (new Materia(codigo: "6683", nombre: "INFRAESTRUCTURA DE REDES")).save()
        (new Materia(codigo: "6699", nombre: "TRAB. PROFESIONAL DE ING. ELECTRONICA")).save()
        (new Materia(codigo: "8601", nombre: "TECNICA DIGITAL")).save()
        (new Materia(codigo: "8602", nombre: "INTRODUCCION A LA INGENIERIA ELECTRONICA")).save()
        (new Materia(codigo: "8603", nombre: "DISPOSITIVOS SEMICONDUCTORES")).save()
        (new Materia(codigo: "8604", nombre: "ANÁLISIS DE CIRCUITOS")).save()
        (new Materia(codigo: "8605", nombre: "SEÑALES Y SISTEMAS")).save()
        (new Materia(codigo: "8606", nombre: "CIRCUITOS ELECTRÓNICOS")).save()
        (new Materia(codigo: "8607", nombre: "LABORATORIO DE MICROPROCESADORES")).save()
        (new Materia(codigo: "8608", nombre: "CONTROL AUTOMATICO I")).save()
        (new Materia(codigo: "8609", nombre: "PROCESOS ESTOCÁSTICOS")).save()
        (new Materia(codigo: "8610", nombre: "DISEÑO DE CIRCUITOS ELECTRÓNICOS")).save()
        (new Materia(codigo: "8611", nombre: "TEORÍA DE LA INFORMACIÓN Y CODIFICACIÓN")).save()
        (new Materia(codigo: "8612", nombre: "COMUNICACIÓN DE DATOS")).save()
        (new Materia(codigo: "8613", nombre: "INSTRUMENTOS ELECTRÓNICOS")).save()
        (new Materia(codigo: "8614", nombre: "INTRODUCCIÓN A PROYECTOS")).save()
        (new Materia(codigo: "8615", nombre: "ROBÓTICA")).save()
        (new Materia(codigo: "8616", nombre: "CONTROL AUTOMÁTICO II")).save()
        (new Materia(codigo: "8618", nombre: "CONTROL INDUSTRIAL DISTRIBUIDO")).save()
        (new Materia(codigo: "8620", nombre: "IDENTIFICACIÓN Y CONTROL ADAPTATIVO")).save()
        (new Materia(codigo: "8621", nombre: "INSTRUMENTACIÓN Y CONTROL DE PROCESOS")).save()
        (new Materia(codigo: "8624", nombre: "ELECTRÓNICA DE POTENCIA")).save()
        (new Materia(codigo: "8625", nombre: "Comunicaciones Digitales I")).save()
        (new Materia(codigo: "8626", nombre: "COMUNICACIONES DIGITALES II")).save()
        (new Materia(codigo: "8627", nombre: "INFRAESTRUCTURA DE REDES FIJAS")).save()
        (new Materia(codigo: "8628", nombre: "LABORATORIO DE COMUNICACIONES")).save()
        (new Materia(codigo: "8629", nombre: "PROPAGACIÓN Y SISTEMAS IRRADIANTES")).save()
        (new Materia(codigo: "8631", nombre: "SERVICIOS Y REDES DE COMUNICACIONES")).save()
        (new Materia(codigo: "8632", nombre: "SISTEMAS INALÁMBRICOS")).save()
        (new Materia(codigo: "8633", nombre: "ELECTRONICA")).save()
        (new Materia(codigo: "8634", nombre: "TRANSMISORES Y RECEPTORES DE COMUNICACIONES")).save()
        (new Materia(codigo: "8635", nombre: "VIDEO DIGITAL")).save()
        (new Materia(codigo: "8636", nombre: "CRIPTOGRAFÍA Y SEGURIDAD INFORMÁTICA")).save()
        (new Materia(codigo: "8637", nombre: "ORGANIZACIÓN DE COMPUTADORAS")).save()
        (new Materia(codigo: "8638", nombre: "ARQUITECTURAS PARALELAS")).save()
        (new Materia(codigo: "8639", nombre: "REDES DE COMPUTADORAS")).save()
        (new Materia(codigo: "8641", nombre: "SISTEMAS DIGITALES")).save()
        (new Materia(codigo: "8643", nombre: "SISTEMAS GRÁFICOS")).save()
        (new Materia(codigo: "8644", nombre: "TÉCNICA DIGITAL AVANZADA")).save()
        (new Materia(codigo: "8647", nombre: "OPTOELECTRÓNICA")).save()
        (new Materia(codigo: "8648", nombre: "SEMINARIO DE ELECTRÓNICA")).save()
        (new Materia(codigo: "8649", nombre: "SEMINARIO DE ELECTRÓNICA II")).save()
        (new Materia(codigo: "8650", nombre: "TECNOLOGÍA DE LOS COMPONENTES")).save()
        (new Materia(codigo: "8651", nombre: "PROCESAMIENTO DE SEÑALES I")).save()
        (new Materia(codigo: "8653", nombre: "Procesamiento del Habla")).save()
        (new Materia(codigo: "8654", nombre: "REDES NEURONALES")).save()
        (new Materia(codigo: "8655", nombre: "Teoría de Detección y Estimación")).save()
        (new Materia(codigo: "8657", nombre: "ACÚSTICA")).save()
        (new Materia(codigo: "8659", nombre: "AUDIO PROFESIONAL")).save()
        (new Materia(codigo: "8660", nombre: "SISTEMAS BIOLÓGICOS")).save()
        (new Materia(codigo: "8661", nombre: "INGENIERÍA BIOMÉDICA")).save()
        (new Materia(codigo: "8662", nombre: "EQUIPAMIENTO PARA DIAGNOSTICO Y TRATAMIENTO")).save()
        (new Materia(codigo: "8663", nombre: "PROCESAMIENTO Y ANÁLISIS DE")).save()
        (new Materia(codigo: "8699", nombre: "TRABAJO PROFESIONAL DE ING. ELECTRÓNICA")).save()
        (new Materia(codigo: "6702", nombre: "MEDIOS DE REPRESENTACION B")).save()
        (new Materia(codigo: "6703", nombre: "MEDIOS DE REPRESENTACION C")).save()
        (new Materia(codigo: "6704", nombre: "TERMODINAMICA I A")).save()
        (new Materia(codigo: "6707", nombre: "DIBUJO MECANICO")).save()
        (new Materia(codigo: "6710", nombre: "CALOR Y TERMODINAMICA")).save()
        (new Materia(codigo: "6711", nombre: "MECANISMOS A")).save()
        (new Materia(codigo: "6712", nombre: "MECANISMOS B")).save()
        (new Materia(codigo: "6713", nombre: "CONOCIMIENTO DE MATERIALES I")).save()
        (new Materia(codigo: "6714", nombre: "CONOCIMIENTO DE MATERIALES II")).save()
        (new Materia(codigo: "6715", nombre: "TECNOLOGIA MECANICA I")).save()
        (new Materia(codigo: "6716", nombre: "ENSAYOS INDUSTRIALES")).save()
        (new Materia(codigo: "6717", nombre: "TALLER")).save()
        (new Materia(codigo: "6718", nombre: "MECANICA DE LOS FLUIDOS B")).save()
        (new Materia(codigo: "6719", nombre: "MAQUINAS ALTERNATIVAS")).save()
        (new Materia(codigo: "6720", nombre: "TURBOMAQUINAS")).save()
        (new Materia(codigo: "6721", nombre: "MEDICIONES FISICAS Y MECANICAS")).save()
        (new Materia(codigo: "6722", nombre: "SISTEMAS DE CONTROL")).save()
        (new Materia(codigo: "6723", nombre: "CONVERSION DE ENERGIA")).save()
        (new Materia(codigo: "6724", nombre: "PROYECTO DE INSTALACIONES INDUSTRIALES")).save()
        (new Materia(codigo: "6725", nombre: "ELEMENTOS DE MAQUINAS")).save()
        (new Materia(codigo: "6726", nombre: "METROLOGIA")).save()
        (new Materia(codigo: "6727", nombre: "TECNOLOGIA MECANICA II")).save()
        (new Materia(codigo: "6728", nombre: "SISTEMAS HIDRAULICOS Y NEUMATICOS")).save()
        (new Materia(codigo: "6729", nombre: "PROYECTO DE MAQUINAS")).save()
        (new Materia(codigo: "6730", nombre: "COMBUSTION")).save()
        (new Materia(codigo: "6731", nombre: "TRANSFERENCIA DE CALOR Y MASA")).save()
        (new Materia(codigo: "6732", nombre: "TECNOLOGIA DEL FRIO")).save()
        (new Materia(codigo: "6733", nombre: "TECNOLOGIA DEL CALOR")).save()
        (new Materia(codigo: "6734", nombre: "PROYECTO DE INSTALACIONES TERMICAS")).save()
        (new Materia(codigo: "6736", nombre: "MECANICA APLICADA")).save()
        (new Materia(codigo: "6737", nombre: "MAQUINAS ENERGETICAS")).save()
        (new Materia(codigo: "6738", nombre: "TECNOLOGIA MECANICA B")).save()
        (new Materia(codigo: "6739", nombre: "DIBUJO PARA INGENIEROS")).save()
        (new Materia(codigo: "6740", nombre: "DISEÑO DE MAQUINAS HERRAMIENTA")).save()
        (new Materia(codigo: "6741", nombre: "AUTOMOTORES")).save()
        (new Materia(codigo: "6743", nombre: "ROBOTICA INDUSTRIAL")).save()
        (new Materia(codigo: "6744", nombre: "PLANTAS TERMICAS")).save()
        (new Materia(codigo: "6745", nombre: "SIST. DE CONTROL EN INSTALAC. TERMICAS")).save()
        (new Materia(codigo: "6746", nombre: "DISEÑO DE INSTALACIONES TERMICAS")).save()
        (new Materia(codigo: "6747", nombre: "METALOGRAFIA")).save()
        (new Materia(codigo: "6748", nombre: "TRATAMIENTOS TERMICOS")).save()
        (new Materia(codigo: "6749", nombre: "METALURGIA FISICA")).save()
        (new Materia(codigo: "6750", nombre: "MATERIALES FERROSOS Y SUS APLICACIONES")).save()
        (new Materia(codigo: "6751", nombre: "MAQUINAS TERMICAS")).save()
        (new Materia(codigo: "6752", nombre: "TERMODINAMICA B")).save()
        (new Materia(codigo: "6756", nombre: "TECNICAS ENERGETICAS")).save()
        (new Materia(codigo: "6758", nombre: "INTR.AL MÉTODO DE LOS ELEM. FINITOS")).save()
        (new Materia(codigo: "6759", nombre: "MECANICA DEL CONTINUO")).save()
        (new Materia(codigo: "6761", nombre: "FUNDAM. MATEMÁT. DE LA VISIÓN ROBÓTICA")).save()
        (new Materia(codigo: "6798", nombre: "TRAB. PROFESIONAL DE ING. MECANICA A")).save()
        (new Materia(codigo: "6799", nombre: "TRAB. PROFESIONAL DE ING. MECANICA B")).save()
        (new Materia(codigo: "8701", nombre: "MEDIOS DE REPRESENTACIÓN C")).save()
        (new Materia(codigo: "8702", nombre: "TERMODINAMICA I A")).save()
        (new Materia(codigo: "8704", nombre: "CONVERSIÓN DE ENERGÍA")).save()
        (new Materia(codigo: "8706", nombre: "MECÁNICA APLICADA")).save()
        (new Materia(codigo: "8707", nombre: "FUENTES Y MAQUINAS ENERGETICAS")).save()
        (new Materia(codigo: "8709", nombre: "TERMODINÁMICA Y MECÁNICA DE FLUIDOS")).save()
        (new Materia(codigo: "8710", nombre: "SISTEMAS DE REPRESENTACIÓN")).save()
        (new Materia(codigo: "8711", nombre: "MEDIOS DE REPRESENTACIÓN A")).save()
        (new Materia(codigo: "8712", nombre: "MECANISMOS")).save()
        (new Materia(codigo: "8713", nombre: "MEDIOS DE REPRESENTACION")).save()
        (new Materia(codigo: "8714", nombre: "TERMODINAMICA")).save()
        (new Materia(codigo: "8715", nombre: "TALLER A")).save()
        (new Materia(codigo: "8717", nombre: "MÁQUINAS TÉRMICAS")).save()
        (new Materia(codigo: "6801", nombre: "CONSTRUCCION DE CARRETERAS")).save()
        (new Materia(codigo: "6802", nombre: "DISEÑO Y OPERACION DE CAMINOS")).save()
        (new Materia(codigo: "6803", nombre: "PUERTOS Y VIAS NAVEGABLES")).save()
        (new Materia(codigo: "6804", nombre: "FERROCARRILES")).save()
        (new Materia(codigo: "6805", nombre: "AEROPUERTOS")).save()
        (new Materia(codigo: "6806", nombre: "TRANSPORTE A")).save()
        (new Materia(codigo: "6807", nombre: "INGENIERIA DEL TRANSPORTE")).save()
        (new Materia(codigo: "6808", nombre: "PLANEAMIENTO DEL TRANSPORTE")).save()
        (new Materia(codigo: "6809", nombre: "TRANSITO")).save()
        (new Materia(codigo: "6810", nombre: "INGENIERIA TERRITORIAL")).save()
        (new Materia(codigo: "6811", nombre: "ORDENAMIENTO RURAL Y URBANO")).save()
        (new Materia(codigo: "6899", nombre: "TRAB. PROF. DE ING. CIVIL (TRANSPORTE)")).save()
        (new Materia(codigo: "8801", nombre: "CONSTRUCCIÓN DE CARRETERAS")).save()
        (new Materia(codigo: "8802", nombre: "DISEÑO Y OPERACIÓN DE CAMINOS")).save()
        (new Materia(codigo: "8803", nombre: "PUERTOS Y VÍAS NAVEGABLES B")).save()
        (new Materia(codigo: "8804", nombre: "FERROCARRILES B")).save()
        (new Materia(codigo: "8805", nombre: "AEROPUERTOS B")).save()
        (new Materia(codigo: "8806", nombre: "PLANEAMIENTO DEL TRANSPORTE")).save()
        (new Materia(codigo: "8807", nombre: "TRÁNSITO")).save()
        (new Materia(codigo: "8808", nombre: "INGENIERÍA TERRITORIAL")).save()
        (new Materia(codigo: "8809", nombre: "ANÁLISIS DE SISTEMAS DE TRANSPORTE")).save()
        (new Materia(codigo: "8810", nombre: "CAMINOS")).save()
        (new Materia(codigo: "8811", nombre: "AEROPUERTOS A")).save()
        (new Materia(codigo: "8812", nombre: "FERROCARRILES A")).save()
        (new Materia(codigo: "8813", nombre: "PUERTOS Y VÍAS NAVEGABLES A")).save()
        (new Materia(codigo: "8814", nombre: "EVALUACIÓN DE PROYECTOS")).save()
        (new Materia(codigo: "6902", nombre: "INGENIERIA SANITARIA")).save()
        (new Materia(codigo: "6903", nombre: "MECANICA DE LOS FLUIDOS A")).save()
        (new Materia(codigo: "6905", nombre: "CENTRALES HIDRAULICAS")).save()
        (new Materia(codigo: "6907", nombre: "HIDROLOGIA")).save()
        (new Materia(codigo: "6909", nombre: "HIDRAULICA FLUVIAL Y MARITIMA")).save()
        (new Materia(codigo: "6910", nombre: "CONSTRUCCIONES HIDRAULICAS")).save()
        (new Materia(codigo: "6999", nombre: "TRAB. PROFESIONAL DE ING. CIVIL(HIDR.)")).save()
        (new Materia(codigo: "8901", nombre: "HIDRÁULICA GENERAL")).save()
        (new Materia(codigo: "8903", nombre: "CENTRALES HIDRÁULICAS")).save()
        (new Materia(codigo: "8905", nombre: "HIDROLOGÍA")).save()
        (new Materia(codigo: "8907", nombre: "CONSTRUCCIONES HIDRÁULICAS")).save()
        (new Materia(codigo: "8909", nombre: "HIDRAULICA APLICADA")).save()
        (new Materia(codigo: "8910", nombre: "APROVECHAMIENTOS HIDRÁULICOS")).save()
        (new Materia(codigo: "8911", nombre: "INGENIERÍA SANITARIA I")).save()
        (new Materia(codigo: "8912", nombre: "GESTIÓN AMBIENTAL EN INGENIERÍA CIVIL")).save()
        (new Materia(codigo: "8913", nombre: "HIDRÁULICA FLUVIAL")).save()
        (new Materia(codigo: "8915", nombre: "LABORATORIO DE HIDRÁULICA")).save()
        (new Materia(codigo: "8917", nombre: "MECÁNICA DE LOS FLUIDOS")).save()
        (new Materia(codigo: "7000", nombre: "TESIS")).save()
        (new Materia(codigo: "7002", nombre: "GEOMETRIA DESCRIPTIVA")).save()
        (new Materia(codigo: "7003", nombre: "MEDIOS DE REPRESENTACION A")).save()
        (new Materia(codigo: "7004", nombre: "DIBUJO TOPOGRAFICO")).save()
        (new Materia(codigo: "7006", nombre: "GEOGRAFIA FISICA Y GEOLOGIA")).save()
        (new Materia(codigo: "7007", nombre: "CALCULO DE COMPENSACION")).save()
        (new Materia(codigo: "7008", nombre: "TOPOGRAFIA I")).save()
        (new Materia(codigo: "7011", nombre: "TOPOGRAFIA III")).save()
        (new Materia(codigo: "7012", nombre: "GEODESIA I")).save()
        (new Materia(codigo: "7013", nombre: "GEODESIA II")).save()
        (new Materia(codigo: "7014", nombre: "FOTOGRAMETRIA I")).save()
        (new Materia(codigo: "7015", nombre: "CARTOGRAFIA")).save()
        (new Materia(codigo: "7017", nombre: "GEODESIA III")).save()
        (new Materia(codigo: "7018", nombre: "CATASTRO Y VALUACIONES")).save()
        (new Materia(codigo: "7019", nombre: "LEVANTAMIENTO Y PRACTICA PROFESIONAL (A)")).save()
        (new Materia(codigo: "7024", nombre: "LEVANTAMIENTOS HIDROGRAFICOS")).save()
        (new Materia(codigo: "7026", nombre: "HIDRAULICA AGRICOLA Y SANEAMIENTO")).save()
        (new Materia(codigo: "7027", nombre: "CATASTRO")).save()
        (new Materia(codigo: "7029", nombre: "TOPOGRAFIA Y GEODESIA")).save()
        (new Materia(codigo: "7030", nombre: "INT. A LOS SISTEMAS DE INF. GEOGRAFICA")).save()
        (new Materia(codigo: "7031", nombre: "INFORMACION RURAL")).save()
        (new Materia(codigo: "7032", nombre: "SISTEMAS DE INFORMACIÓN GEOGRÁFICA")).save()
        (new Materia(codigo: "7033", nombre: "ELEMENTOS DE CONSTRUCCIÓN")).save()
        (new Materia(codigo: "7034", nombre: "TOPOGRAFÍA III")).save()
        (new Materia(codigo: "7036", nombre: "SISTEMAS CARTOGRÁFICOS Y TELEDETECCIÓN")).save()
        (new Materia(codigo: "7037", nombre: "LEVANTAMIENTO Y PRÁCTICA PROFESIONAL I")).save()
        (new Materia(codigo: "7040", nombre: "GEOLOGÍA APLICADA")).save()
        (new Materia(codigo: "7044", nombre: "DIBUJO TOPOGRÁFICO II")).save()
        (new Materia(codigo: "7099", nombre: "TRABAJO PROF. DE LA ING. EN AGRIMENSURA")).save()
        (new Materia(codigo: "9001", nombre: "TOPOGRAFÍA Y GEODESIA")).save()
        (new Materia(codigo: "7101", nombre: "INTR. A LA ECONOMIA Y ORG. DE LA EMPRESA")).save()
        (new Materia(codigo: "7102", nombre: "AGRIMENSURA LEGAL I")).save()
        (new Materia(codigo: "7103", nombre: "ESTADISTICA TECNICA")).save()
        (new Materia(codigo: "7104", nombre: "ORGANIZACION INDUSTRIAL I")).save()
        (new Materia(codigo: "7105", nombre: "ORGANIZACION INDUSTRIAL II")).save()
        (new Materia(codigo: "7106", nombre: "ESTRUCTURA ECONOMICA ARGENTINA")).save()
        (new Materia(codigo: "7107", nombre: "INVESTIGACION OPERATIVA")).save()
        (new Materia(codigo: "7108", nombre: "ORGANIZACION INDUSTRIAL III")).save()
        (new Materia(codigo: "7111", nombre: "ORGANIZACION DE OBRAS")).save()
        (new Materia(codigo: "7112", nombre: "ESTRUCTURA DE LAS ORGANIZACIONES")).save()
        (new Materia(codigo: "7113", nombre: "INFORMACION EN LAS ORGANIZACIONES")).save()
        (new Materia(codigo: "7114", nombre: "MODELOS Y OPTIMIZACION I")).save()
        (new Materia(codigo: "7115", nombre: "MODELOS Y OPTIMIZACION II")).save()
        (new Materia(codigo: "7116", nombre: "ADMINISTRACION DE PROYECTOS")).save()
        (new Materia(codigo: "7117", nombre: "DERECHO INFORMATICO")).save()
        (new Materia(codigo: "7118", nombre: "ESTRUCTURA ECONOMICA ARGENTINA")).save()
        (new Materia(codigo: "7120", nombre: "MODELOS Y OPTIMIZACION III")).save()
        (new Materia(codigo: "7121", nombre: "LEG. Y EJER. PROF. DE LA ING. CIVIL")).save()
        (new Materia(codigo: "7122", nombre: "LEG. Y EJER. PROF. DE LA ING. INDUSTRIAL")).save()
        (new Materia(codigo: "7123", nombre: "ECONOMIA")).save()
        (new Materia(codigo: "7125", nombre: "LEG. Y EJER. PROF. DE LA ING. MECANICA")).save()
        (new Materia(codigo: "7127", nombre: "LEG. Y EJ. PROF. DE LA ING. ELECTRONICA")).save()
        (new Materia(codigo: "7128", nombre: "LEG. Y EJER. PROF. DE LA ING. QUIMICA")).save()
        (new Materia(codigo: "7130", nombre: "AGRIMENSURA LEGAL III")).save()
        (new Materia(codigo: "7131", nombre: "ORGANIZACION DE LA PRODUCCION")).save()
        (new Materia(codigo: "7132", nombre: "INVESTIGACION OPERATIVA SUPERIOR")).save()
        (new Materia(codigo: "7133", nombre: "COMERCIALIZACION DE PRODUCTOS INDUST.")).save()
        (new Materia(codigo: "7134", nombre: "GESTION PRESUPUESTARIA")).save()
        (new Materia(codigo: "7135", nombre: "ESTADISTICA TECNICA SUPERIOR")).save()
        (new Materia(codigo: "7136", nombre: "GESTION DE CALIDAD")).save()
        (new Materia(codigo: "7137", nombre: "DIRECCION DE MANUFACTURA")).save()
        (new Materia(codigo: "7138", nombre: "LEGISLACION GENERAL")).save()
        (new Materia(codigo: "7139", nombre: "LEG. Y EJ. PROF. DE LA ING. ELECTRIC. B")).save()
        (new Materia(codigo: "7140", nombre: "LEG. Y EJ. PROF. DE LA ING. EN INFORMAT.")).save()
        (new Materia(codigo: "7141", nombre: "ANÁLISIS Y RESOLUCIÓN DE PROBLEMAS")).save()
        (new Materia(codigo: "7143", nombre: "LOGISTICA INTEGRAL")).save()
        (new Materia(codigo: "7144", nombre: "RECURSOS HUMANOS")).save()
        (new Materia(codigo: "7145", nombre: "INFORMATICA PARA LA GESTION DE EMPRESAS")).save()
        (new Materia(codigo: "7146", nombre: "INGENIERIA ECONOMICA")).save()
        (new Materia(codigo: "7150", nombre: "INGENIERIA ECONOMICA I")).save()
        (new Materia(codigo: "7151", nombre: "INGENIERIA ECONOMICA II")).save()
        (new Materia(codigo: "7153", nombre: "EVAL. DE PROYECTOS DE PLANTAS QUÍMICAS")).save()
        (new Materia(codigo: "7155", nombre: "ECONOMIA DE LA EMPRESA ALIMENTARIA")).save()
        (new Materia(codigo: "7156", nombre: "LEG. Y EJ. PROF. DE LA ING. DE ALIMENTOS")).save()
        (new Materia(codigo: "7158", nombre: "ANÁLISIS Y RESOL. DE PROBL. DE SISTEMAS")).save()
        (new Materia(codigo: "9102", nombre: "GERENCIAMIENTO Y ORGANIZACIÓN DE OBRAS")).save()
        (new Materia(codigo: "9103", nombre: "ESTADISTICA APLICADA I")).save()
        (new Materia(codigo: "9104", nombre: "MODELOS Y OPTIMIZACIÓN I")).save()
        (new Materia(codigo: "9107", nombre: "INVESTIGACION OPERATIVA I")).save()
        (new Materia(codigo: "9108", nombre: "ORGANIZACIÓN INDUSTRIAL III")).save()
        (new Materia(codigo: "9109", nombre: "ECONOMIA")).save()
        (new Materia(codigo: "9110", nombre: "ORGANIZACIÓN INDUSTRIAL I")).save()
        (new Materia(codigo: "9111", nombre: "LEGISLACIÓN Y EJERCICIO PROFESIONAL")).save()
        (new Materia(codigo: "9112", nombre: "ORGANIZACIÓN INDUSTRIAL II")).save()
        (new Materia(codigo: "9113", nombre: "ORGANIZACIÓN DE LA PRODUCCIÓN")).save()
        (new Materia(codigo: "9114", nombre: "INFORMÁTICA PARA LA GESTIÓN DE EMPRESAS")).save()
        (new Materia(codigo: "9115", nombre: "LEGISLACIÓN Y EJERCICIO PROFESIONAL")).save()
        (new Materia(codigo: "9116", nombre: "LEGISLACIÓN Y EJERCICIO PROFESIONAL")).save()
        (new Materia(codigo: "9117", nombre: "RECURSOS HUMANOS")).save()
        (new Materia(codigo: "9119", nombre: "INTROD. ECONOMÍA Y ORG. DE LA EMPRESA")).save()
        (new Materia(codigo: "9120", nombre: "COMERCIALIZACIÓN")).save()
        (new Materia(codigo: "9121", nombre: "CONFLICTO Y NEGOCIACIÓN")).save()
        (new Materia(codigo: "9122", nombre: "INGENIERÍA LEGAL PARA INGENIERÍA INDUSTRIAL")).save()
        (new Materia(codigo: "9124", nombre: "MACROECONOMÍA Y ESTRUCTURA ECONÓMICA")).save()
        (new Materia(codigo: "9125", nombre: "ESTADÍSTICA APLICADA III")).save()
        (new Materia(codigo: "9126", nombre: "DIRECCIÓN DE MANUFACTURA")).save()
        (new Materia(codigo: "9128", nombre: "GESTIÓN DE COSTOS")).save()
        (new Materia(codigo: "9129", nombre: "INGENIERÍA ECONÓMICA A")).save()
        (new Materia(codigo: "9130", nombre: "ESTADÍSTICA APLICADA II")).save()
        (new Materia(codigo: "9131", nombre: "INVESTIGACIÓN OPERATIVA II")).save()
        (new Materia(codigo: "9132", nombre: "INVESTIGACIÓN OPERATIVA III")).save()
        (new Materia(codigo: "9133", nombre: "MICROECONOMÍA APLICADA")).save()
        (new Materia(codigo: "9134", nombre: "GESTIÓN FINANCIERA")).save()
        (new Materia(codigo: "9135", nombre: "ANÁLISIS DE CASOS")).save()
        (new Materia(codigo: "9136", nombre: "GESTIÓN DE CALIDAD")).save()
        (new Materia(codigo: "9139", nombre: "ESTRUCTURAS Y PROCESOS ORGANIZACIONALES")).save()
        (new Materia(codigo: "9141", nombre: "ECONOMÍA DE LAS ORGANIZACIONES")).save()
        (new Materia(codigo: "7200", nombre: "TESIS DE INGENIERIA INDUSTRIAL")).save()
        (new Materia(codigo: "7201", nombre: "MATERIALES INDUSTRIALES I")).save()
        (new Materia(codigo: "7202", nombre: "INDUSTRIAS I")).save()
        (new Materia(codigo: "7204", nombre: "INDUSTRIAS DE PROCESOS DE CONFORMACION")).save()
        (new Materia(codigo: "7205", nombre: "ARQUITECTURA INDUSTRIAL")).save()
        (new Materia(codigo: "7206", nombre: "AUTOMATIZACION INDUSTRIAL")).save()
        (new Materia(codigo: "7207", nombre: "INDUSTRIAS III")).save()
        (new Materia(codigo: "7209", nombre: "INDUSTRIAS PLASTICAS")).save()
        (new Materia(codigo: "7210", nombre: "INDUSTRIAS DE CELULOSA Y PAPEL")).save()
        (new Materia(codigo: "7211", nombre: "INDUSTRIAS PETROQUIMICAS")).save()
        (new Materia(codigo: "7212", nombre: "INDUSTRIAS TEXTILES")).save()
        (new Materia(codigo: "7213", nombre: "MATERIALES INDUSTRIALES II")).save()
        (new Materia(codigo: "7214", nombre: "DISEÑO DE PRODUCTO")).save()
        (new Materia(codigo: "7215", nombre: "INDUSTRIAS DE ALIMENTACION")).save()
        (new Materia(codigo: "7217", nombre: "INDUSTRIAS PETROLIFERAS")).save()
        (new Materia(codigo: "7218", nombre: "INDUSTRIAS II")).save()
        (new Materia(codigo: "7299", nombre: "TRABAJO PROFESIONAL DE ING. INDUSTRIAL")).save()
        (new Materia(codigo: "9201", nombre: "MATERIALES INDUSTRIALES I")).save()
        (new Materia(codigo: "9202", nombre: "INDUSTRIAS I")).save()
        (new Materia(codigo: "9203", nombre: "INTRODUCCIÓN A LA INGENIERÍA INDUSTRIA")).save()
        (new Materia(codigo: "9204", nombre: "PROCESOS DE MANUFACTURA I")).save()
        (new Materia(codigo: "9205", nombre: "EDIFICIOS INDUSTRIALES")).save()
        (new Materia(codigo: "9206", nombre: "AUTOMATIZACIÓN INDUSTRIAL Y ROBÓTICA")).save()
        (new Materia(codigo: "9207", nombre: "INSTALACIONES INDUSTRIALES")).save()
        (new Materia(codigo: "9208", nombre: "DISEÑO DE PRODUCTOS")).save()
        (new Materia(codigo: "9209", nombre: "INDUSTRIAS PLÁSTICAS")).save()
        (new Materia(codigo: "9210", nombre: "INDUSTRIAS DE CELULOSA Y PAPEL")).save()
        (new Materia(codigo: "9211", nombre: "INDUSTRIAS PETROQUÍMICAS")).save()
        (new Materia(codigo: "9212", nombre: "INDUSTRIAS TEXTILES")).save()
        (new Materia(codigo: "9213", nombre: "MATERIALES INDUSTRIALES II")).save()
        (new Materia(codigo: "9215", nombre: "INDUSTRIAS DE LA ALIMENTACIÓN")).save()
        (new Materia(codigo: "9216", nombre: "SEMINARIO DE INGENIERÍA INDUSTRIAL II")).save()
        (new Materia(codigo: "9217", nombre: "INDUSTRIAS PETROLÍFERAS")).save()
        (new Materia(codigo: "9218", nombre: "INDUSTRIAS II")).save()
        (new Materia(codigo: "9219", nombre: "PROCESOS DE MANUFACTURA II")).save()
        (new Materia(codigo: "9299", nombre: "TRABAJO PROFESIONAL DE INGENIERÍA INDUSTRIAL")).save()
        (new Materia(codigo: "7301", nombre: "ARQUITECTURA NAVAL I")).save()
        (new Materia(codigo: "7302", nombre: "CONSTRUCCION NAVAL I")).save()
        (new Materia(codigo: "7303", nombre: "ARQUITECTURA NAVAL II")).save()
        (new Materia(codigo: "7304", nombre: "ESTRUCTURA DE BUQUES")).save()
        (new Materia(codigo: "7305", nombre: "INTRODUCCION A LAS MAQUINAS MARINAS")).save()
        (new Materia(codigo: "7306", nombre: "VIBRACIONES DE ESTRUCTURAS")).save()
        (new Materia(codigo: "7307", nombre: "CONSTRUCCION NAVAL II")).save()
        (new Materia(codigo: "7309", nombre: "PROYECTO DE BUQUES I")).save()
        (new Materia(codigo: "7310", nombre: "PROYECTO DE BUQUES II")).save()
        (new Materia(codigo: "7311", nombre: "MAQUINAS MARINAS I")).save()
        (new Materia(codigo: "7312", nombre: "MAQUINAS MARINAS II")).save()
        (new Materia(codigo: "7314", nombre: "NAVEGACION")).save()
        (new Materia(codigo: "7315", nombre: "MAQUINAS MARINAS III")).save()
        (new Materia(codigo: "7316", nombre: "CONSTRUCCION NAVAL III")).save()
        (new Materia(codigo: "7401", nombre: "HORMIGON I")).save()
        (new Materia(codigo: "7403", nombre: "ARQUITECTURA Y PLANIFICACION")).save()
        (new Materia(codigo: "7404", nombre: "CONSTRUCCIONES")).save()
        (new Materia(codigo: "7405", nombre: "HORMIGON II")).save()
        (new Materia(codigo: "7407", nombre: "INSTALACIONES DE EDIFICIOS")).save()
        (new Materia(codigo: "7408", nombre: "PRESAS")).save()
        (new Materia(codigo: "7409", nombre: "MAQUINARIAS DE LA CONSTRUCCION")).save()
        (new Materia(codigo: "7411", nombre: "CIMENTACIONES")).save()
        (new Materia(codigo: "7412", nombre: "ESTRUCTURAS METALICAS I")).save()
        (new Materia(codigo: "7413", nombre: "ESTRUCTURAS METALICAS II")).save()
        (new Materia(codigo: "7414", nombre: "TECNOLOGIA DEL HORMIGON")).save()
        (new Materia(codigo: "7415", nombre: "PATOLOGIA DE LA CONSTRUCCION")).save()
        (new Materia(codigo: "7416", nombre: "ESTRUCTURAS DE MADERA")).save()
        (new Materia(codigo: "7417", nombre: "SISTEMAS CONSTRUCTIVOS")).save()
        (new Materia(codigo: "7418", nombre: "SISTEMAS ESTRUCTURALES")).save()
        (new Materia(codigo: "7421", nombre: "INSP. Y EJEC. DE ESTRUC. DE HORMIGON")).save()
        (new Materia(codigo: "7499", nombre: "TRAB. PROFESIONAL DE ING. CIVIL (CONST.)")).save()
        (new Materia(codigo: "9401", nombre: "HORMIGON I")).save()
        (new Materia(codigo: "9402", nombre: "ARQUITECTURA Y PLANIFICACIÓN URBANA")).save()
        (new Materia(codigo: "9403", nombre: "CONSTRUCCIONES")).save()
        (new Materia(codigo: "9404", nombre: "HORMIGÓN II")).save()
        (new Materia(codigo: "9405", nombre: "INSTALACIONES EN OBRAS CIVILES I")).save()
        (new Materia(codigo: "9406", nombre: "PRESAS")).save()
        (new Materia(codigo: "9407", nombre: "MAQUINARIAS DE LA CONSTRUCCIÓN")).save()
        (new Materia(codigo: "9409", nombre: "GEOTÉCNICA APLICADA")).save()
        (new Materia(codigo: "9410", nombre: "ESTRUCTURAS METÁLICAS I")).save()
        (new Materia(codigo: "9411", nombre: "ESTRUCTURAS METÁLICAS II")).save()
        (new Materia(codigo: "9412", nombre: "TECNOLOGIA DEL HORMIGON")).save()
        (new Materia(codigo: "9413", nombre: "PATOLOGÍA DE LA CONSTRUCCIÓN")).save()
        (new Materia(codigo: "9414", nombre: "ESTRUCTURAS DE MADERA")).save()
        (new Materia(codigo: "9415", nombre: "SISTEMAS CONSTRUCTIVOS")).save()
        (new Materia(codigo: "9416", nombre: "SISTEMAS ESTRUCTURALES")).save()
        (new Materia(codigo: "9418", nombre: "INSPECCIÓN Y EJECUCIÓN DE ESTRUCTURAS")).save()
        (new Materia(codigo: "9419", nombre: "MATERIALES NO TRADICIONALES EN")).save()
        (new Materia(codigo: "7501", nombre: "COMPUTACION")).save()
        (new Materia(codigo: "7502", nombre: "ALGORITMOS Y PROGRAMACION I")).save()
        (new Materia(codigo: "7503", nombre: "ORGANIZACION DEL COMPUTADOR")).save()
        (new Materia(codigo: "7504", nombre: "ALGORITMOS Y PROGRAMACION II")).save()
        (new Materia(codigo: "7506", nombre: "ORGANIZACION DE DATOS")).save()
        (new Materia(codigo: "7507", nombre: "ALGORITMOS Y PROGRAMACION III")).save()
        (new Materia(codigo: "7508", nombre: "SISTEMAS OPERATIVOS")).save()
        (new Materia(codigo: "7509", nombre: "ANALISIS DE LA INFORMACION")).save()
        (new Materia(codigo: "7510", nombre: "TECNICAS DE DISEÑO")).save()
        (new Materia(codigo: "7512", nombre: "ANALISIS NUMERICO I")).save()
        (new Materia(codigo: "7514", nombre: "LENGUAJES FORMALES")).save()
        (new Materia(codigo: "7515", nombre: "BASE DE DATOS")).save()
        (new Materia(codigo: "7517", nombre: "IMPLANTACION DE SISTEMAS")).save()
        (new Materia(codigo: "7518", nombre: "PROYECTOS INFORMATICOS")).save()
        (new Materia(codigo: "7519", nombre: "TEORIA DE COMUNICACION")).save()
        (new Materia(codigo: "7523", nombre: "INTELIGENCIA ARTIFICIAL")).save()
        (new Materia(codigo: "7524", nombre: "TEORIA DE LA PROGRAMACION")).save()
        (new Materia(codigo: "7526", nombre: "SIMULACION")).save()
        (new Materia(codigo: "7527", nombre: "ALGORITMOS Y PROGRAMACION IV")).save()
        (new Materia(codigo: "7528", nombre: "BASE DE DATOS B")).save()
        (new Materia(codigo: "7529", nombre: "TEORIA DE ALGORITMOS I")).save()
        (new Materia(codigo: "7531", nombre: "TEORIA DE LENGUAJE")).save()
        (new Materia(codigo: "7533", nombre: "REDES Y TELEPROCESAMIENTOS I")).save()
        (new Materia(codigo: "7538", nombre: "ANALISIS NUMERICO II A")).save()
        (new Materia(codigo: "7539", nombre: "APLICACIONES INFORMATICAS")).save()
        (new Materia(codigo: "7540", nombre: "ALGORITMOS Y PROGRAMACION I")).save()
        (new Materia(codigo: "7541", nombre: "ALGORITMOS Y PROGRAMACION II")).save()
        (new Materia(codigo: "7542", nombre: "TALLER DE PROGRAMACION I")).save()
        (new Materia(codigo: "7543", nombre: "INTRODUCCION A LOS SISTEMAS DISTRIBUIDOS")).save()
        (new Materia(codigo: "7544", nombre: "ADM. Y CONTROL DE PROY. INFORMATICOS I")).save()
        (new Materia(codigo: "7545", nombre: "TALLER DE DESARROLLO DE PROYECTOS I")).save()
        (new Materia(codigo: "7546", nombre: "ADM. Y CONTROL DE PROY. INFORMATICOS II")).save()
        (new Materia(codigo: "7547", nombre: "TALLER DE DESARROLLO DE PROYECTOS II")).save()
        (new Materia(codigo: "7548", nombre: "CALIDAD EN DESARROLLO DE SISTEMAS")).save()
        (new Materia(codigo: "7550", nombre: "INTRODUCCION A LOS SISTEMAS INTELIGENTES")).save()
        (new Materia(codigo: "7552", nombre: "TALLER DE PROGRAMACION II")).save()
        (new Materia(codigo: "7556", nombre: "ORG. DE LA IMPLANTACION Y EL MANTENIM.")).save()
        (new Materia(codigo: "7557", nombre: "MODELOS DE PROCESOS DE DESARROLLO")).save()
        (new Materia(codigo: "7559", nombre: "TECNICAS DE PROGRAMACION CONCURRENTE I")).save()
        (new Materia(codigo: "7561", nombre: "TALLER DE PROGRAMACION III")).save()
        (new Materia(codigo: "7565", nombre: "MANUFACTURA INTEGRADA POR COMP.(CIM) I")).save()
        (new Materia(codigo: "7567", nombre: "SIST.AUTOM.DE DIAG.Y DETEC.DE FALLAS I")).save()
        (new Materia(codigo: "7570", nombre: "SIST.DE PROG. NO CONVENCIONAL DE ROBOTS")).save()
        (new Materia(codigo: "7571", nombre: "SEMINARIO DE ING. EN INFORMATICA I")).save()
        (new Materia(codigo: "7573", nombre: "ARQUITECTURA DEL SOFTWARE")).save()
        (new Materia(codigo: "7574", nombre: "SISTEMAS DISTRIBUIDOS I")).save()
        (new Materia(codigo: "9501", nombre: "COMPUTACIÓN")).save()
        (new Materia(codigo: "9502", nombre: "ALGORITMOS Y PROGRAMACIÓN III")).save()
        (new Materia(codigo: "9503", nombre: "SISTEMAS OPERATIVOS")).save()
        (new Materia(codigo: "9504", nombre: "ANÁLISIS NUMÉRICO I")).save()
        (new Materia(codigo: "9505", nombre: "BASE DE DATOS")).save()
        (new Materia(codigo: "9506", nombre: "TEORÍA DE ALGORITMOS I")).save()
        (new Materia(codigo: "9507", nombre: "TEORÍA DE LENGUAJE")).save()
        (new Materia(codigo: "9508", nombre: "TALLER DE PROGRAMACIÓN I")).save()
        (new Materia(codigo: "9509", nombre: "TÉCNICAS DE PROGRAMACIÓN CONCURRENTE I")).save()
        (new Materia(codigo: "9510", nombre: "MODELACION NUMERICA")).save()
        (new Materia(codigo: "9511", nombre: "ALGORITMOS Y PROGRAMACIÓN I")).save()
        (new Materia(codigo: "9512", nombre: "ALGORITMOS Y PROGRAMACIÓN II")).save()
        (new Materia(codigo: "9513", nombre: "MÉTODOS MATEMÁTICOS Y NUMÉRICOS")).save()
        (new Materia(codigo: "9514", nombre: "ALGORITMOS Y PROGRAMACIÓN I")).save()
        (new Materia(codigo: "9515", nombre: "ALGORITMOS Y PROGRAMACIÓN II")).save()
        (new Materia(codigo: "9520", nombre: "METODOS Y MODELOS EN LA INGENIERIA DEL")).save()
        (new Materia(codigo: "9524", nombre: "ADMINISTRACION Y CONTROL DE PROYECTOS")).save()
        (new Materia(codigo: "9525", nombre: "INTELIGENCIA ARTIFICIAL")).save()
        (new Materia(codigo: "9557", nombre: "ORGANIZACIÓN DEL COMPUTADOR")).save()
        (new Materia(codigo: "9558", nombre: "ORGANIZACIÓN DE DATOS")).save()
        (new Materia(codigo: "7601", nombre: "INTRODUCCION A LA INGENIERIA QUIMICA I")).save()
        (new Materia(codigo: "7602", nombre: "INTRODUCCION A LA INGENIERIA QUIMICA II")).save()
        (new Materia(codigo: "7603", nombre: "OPERACIONES UNITARIAS I")).save()
        (new Materia(codigo: "7604", nombre: "OPERACIONES UNITARIAS II")).save()
        (new Materia(codigo: "7605", nombre: "OPERACIONES UNITARIAS III")).save()
        (new Materia(codigo: "7607", nombre: "INGENIERIA DE LAS INSTALACIONES II")).save()
        (new Materia(codigo: "7608", nombre: "INGENIERIA DE LAS REACCIONES QUIMICAS")).save()
        (new Materia(codigo: "7609", nombre: "INSTRUMEN. Y CONTROL DE PLANTAS QUIMICAS")).save()
        (new Materia(codigo: "7612", nombre: "MICROBIOLOGIA INDUSTRIAL")).save()
        (new Materia(codigo: "7613", nombre: "BIOINGENIERIA INDUSTRIAL")).save()
        (new Materia(codigo: "7616", nombre: "ELECTROQUIMICA")).save()
        (new Materia(codigo: "7622", nombre: "FUNDAMENTOS DE LA ING. DE RESERVORIOS")).save()
        (new Materia(codigo: "7627", nombre: "CONTROL ESTADISTICO DE PROCESOS")).save()
        (new Materia(codigo: "7628", nombre: "GEST DE RECURSOS EN LA IND. DE PROCESOS")).save()
        (new Materia(codigo: "7629", nombre: "INDUSTRIA DE PROCESOS")).save()
        (new Materia(codigo: "7632", nombre: "PRESERVACION DE ALIMENTOS")).save()
        (new Materia(codigo: "7640", nombre: "INTRODUCCION A LA BIOQUIMICA")).save()
        (new Materia(codigo: "7641", nombre: "BIOTECNOLOGÍA")).save()
        (new Materia(codigo: "7642", nombre: "INGENIERIA DE LAS INSTALACIONES II B")).save()
        (new Materia(codigo: "7643", nombre: "INSTRUMENTACION Y CONTROL")).save()
        (new Materia(codigo: "7644", nombre: "PRÁCTICA PROFESIONAL")).save()
        (new Materia(codigo: "7645", nombre: "TERMODINÁMICA DE LOS PROCESOS")).save()
        (new Materia(codigo: "7646", nombre: "INTRODUCCIÓN A LA INGENIERÍA QUÍMICA")).save()
        (new Materia(codigo: "7647", nombre: "FENÓMENOS DE TRANSPORTE")).save()
        (new Materia(codigo: "7648", nombre: "EVALUACIÓN DE PROPIEDADES FÍSICAS")).save()
        (new Materia(codigo: "7649", nombre: "OPER. UNIT. TRANSF. CANT. MOV. Y ENERGÍA")).save()
        (new Materia(codigo: "7652", nombre: "OPER. UNIT. DE TRANSF. DE MATERIA")).save()
        (new Materia(codigo: "7653", nombre: "DISEÑO DE REACTORES")).save()
        (new Materia(codigo: "7654", nombre: "INSTALACIONES DE PLANTAS DE PROCESOS")).save()
        (new Materia(codigo: "7655", nombre: "MICROBIOLOGÍA INDUSTRIAL")).save()
        (new Materia(codigo: "7656", nombre: "INSTR. Y CONTROL DE PLANTAS QUÍMICAS")).save()
        (new Materia(codigo: "7657", nombre: "DISEÑO DE PROCESOS")).save()
        (new Materia(codigo: "7658", nombre: "EMISIONES DE CONT. QUÍMICOS Y BIOLÓGICOS")).save()
        (new Materia(codigo: "7659", nombre: "TRABAJO PROFESIONAL I")).save()
        (new Materia(codigo: "7660", nombre: "LABORATORIO DE OPERACIONES Y PROCESOS")).save()
        (new Materia(codigo: "7661", nombre: "BIOINGENIERÍA")).save()
        (new Materia(codigo: "7699", nombre: "TRABAJO PROFESIONAL DE ING. QUÍMICA")).save()
        (new Materia(codigo: "7701", nombre: "HIGIENE Y SEGURIDAD DEL TRABAJO")).save()
        (new Materia(codigo: "7702", nombre: "INTRODUCCION A LA INGENIERIA AMBIENTAL")).save()
        (new Materia(codigo: "7705", nombre: "PROYECTOS NACIONALES E ING. AMBIENTAL")).save()
        (new Materia(codigo: "7708", nombre: "SEGURIDAD AMBIENTAL Y DEL TRABAJO B")).save()
        (new Materia(codigo: "7709", nombre: "SEGURIDAD AMBIENTAL Y DEL TRABAJO A")).save()
        (new Materia(codigo: "7741", nombre: "GESTION AMBIENTAL EN LA IND. ALIMENTARIA")).save()
        (new Materia(codigo: "9701", nombre: "HIGIENE Y SEGURIDAD INDUSTRIAL")).save()
        (new Materia(codigo: "9702", nombre: "SEGURIDAD AMBIENTAL Y DEL TRABAJO B")).save()
        (new Materia(codigo: "9703", nombre: "HIGIENE Y SEGURIDAD EN OBRAS CIVILES")).save()
        (new Materia(codigo: "9704", nombre: "SEGURIDAD AMBIENTAL Y DEL TRABAJO")).save()
        (new Materia(codigo: "9705", nombre: "GESTIÓN AMBIENTAL")).save()
        (new Materia(codigo: "7801", nombre: "IDIOMA INGLES")).save()
        (new Materia(codigo: "7802", nombre: "IDIOMA ALEMAN")).save()
        (new Materia(codigo: "7803", nombre: "IDIOMA FRANCES")).save()
        (new Materia(codigo: "7804", nombre: "IDIOMA ITALIANO")).save()
        (new Materia(codigo: "7805", nombre: "IDIOMA PORTUGUES")).save()
        (new Materia(codigo: "9801", nombre: "IDIOMA INGLES")).save()
        (new Materia(codigo: "9802", nombre: "IDIOMA ALEMAN")).save()
        (new Materia(codigo: "9803", nombre: "IDIOMA FRANCES")).save()
        (new Materia(codigo: "9804", nombre: "IDIOMA ITALIANO")).save()
        (new Materia(codigo: "9805", nombre: "IDIOMA PORTUGUES")).save()

        
    }
    def destroy = {
    }
}
